name: Build macOS

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_INCREMENTAL: "0"
  RUST_BACKTRACE: short

jobs:
  build-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            artifact: clash-verge-aarch64-dmg
          - target: x86_64-apple-darwin
            artifact: clash-verge-x86_64-dmg

    name: build ${{ matrix.target }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.95.0"
          targets: ${{ matrix.target }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> target"

      - name: Install x86 OpenSSL
        if: matrix.target == 'x86_64-apple-darwin'
        run: |
          arch -x86_64 brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=$(brew --prefix openssl@3)/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=$(brew --prefix openssl@3)/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "24.16.0"

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies and prebuild
        run: |
          pnpm i
          pnpm run prebuild ${{ matrix.target }}

      - name: Build DMG
        run: pnpm tauri build --target ${{ matrix.target }}
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: target/${{ matrix.target }}/release/bundle/dmg/*.dmg
          if-no-files-found: error
